const COUNTRY_FLAG_CODES = {
    "albania": "al",
    "algeria": "dz",
    "argentina": "ar",
    "armenia": "am",
    "australia": "au",
    "austria": "at",
    "azerbaijan": "az",
    "bahrain": "bh",
    "bangladesh": "bd",
    "belgium": "be",
    "bolivia": "bo",
    "bosnia and herzegovina": "ba",
    "brazil": "br",
    "bulgaria": "bg",
    "cambodia": "kh",
    "canada": "ca",
    "chile": "cl",
    "china": "cn",
    "colombia": "co",
    "costa rica": "cr",
    "croatia": "hr",
    "czech republic": "cz",
    "denmark": "dk",
    "dominican republic": "do",
    "ecuador": "ec",
    "egypt": "eg",
    "el salvador": "sv",
    "estonia": "ee",
    "ethiopia": "et",
    "finland": "fi",
    "france": "fr",
    "georgia": "ge",
    "germany": "de",
    "ghana": "gh",
    "greece": "gr",
    "guatemala": "gt",
    "honduras": "hn",
    "hong kong": "hk",
    "hungary": "hu",
    "iceland": "is",
    "india": "in",
    "indonesia": "id",
    "iran": "ir",
    "iraq": "iq",
    "ireland": "ie",
    "israel": "il",
    "italy": "it",
    "japan": "jp",
    "jordan": "jo",
    "kazakhstan": "kz",
    "kenya": "ke",
    "kuwait": "kw",
    "laos": "la",
    "latvia": "lv",
    "lebanon": "lb",
    "lithuania": "lt",
    "malaysia": "my",
    "mauritania": "mr",
    "mexico": "mx",
    "mongolia": "mn",
    "morocco": "ma",
    "myanmar": "mm",
    "nepal": "np",
    "netherlands": "nl",
    "new zealand": "nz",
    "nicaragua": "ni",
    "nigeria": "ng",
    "north macedonia": "mk",
    "norway": "no",
    "oman": "om",
    "pakistan": "pk",
    "palestine": "ps",
    "panama": "pa",
    "paraguay": "py",
    "peru": "pe",
    "philippines": "ph",
    "poland": "pl",
    "portugal": "pt",
    "puerto rico": "pr",
    "qatar": "qa",
    "romania": "ro",
    "russia": "ru",
    "saudi arabia": "sa",
    "serbia": "rs",
    "singapore": "sg",
    "slovakia": "sk",
    "slovenia": "si",
    "south africa": "za",
    "south korea": "kr",
    "spain": "es",
    "sri lanka": "lk",
    "sweden": "se",
    "switzerland": "ch",
    "syria": "sy",
    "taiwan": "tw",
    "tanzania": "tz",
    "thailand": "th",
    "tunisia": "tn",
    "turkey": "tr",
    "uae": "ae",
    "ukraine": "ua",
    "united arab emirates": "ae",
    "united kingdom": "gb",
    "united states": "us",
    "uruguay": "uy",
    "uzbekistan": "uz",
    "venezuela": "ve",
    "vietnam": "vn",
    "yemen": "ye",
};

export const getCountryFlagCode = (country) => {
    if (typeof country !== "string") return "";
    return COUNTRY_FLAG_CODES[country.trim().toLowerCase()] ?? "";
};

export const getLanguageDisplayLabel = ({ language, country }) => {
    return `${language} (${country})`;
};
